E_Learning-MVC-Project/ViewComponents/FooterViewComponent.cs
using E_Learning_MVC_Project.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace E_Learning_MVC_Project.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private readonly ISettingService _settigservice;

        public FooterViewComponent(ISettingService settingService)
        {
            _settigservice = settingService;


        }
        public async Task<IViewComponentResult> InvokeAsync()
        {


            Dictionary<string, string> settings = await _settigservice.GetAllAsync();
            FooterVMVC response = new()
            {
                Settings = settings

            };
            return await Task.FromResult(View(response));
        }
        public class FooterVMVC
        {


            public Dictionary<string, string> Settings { get; set; }


        }

    }
}

E_Learning-MVC-Project/ViewComponents/HeaderViewComponent.cs
using E_Learning_MVC_Project.Models;
using E_Learning_MVC_Project.Services.Interface;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace E_Learning_MVC_Project.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {

        private readonly ISettingService _settigservice;
        private readonly UserManager<AppUser> _userManager;

        public HeaderViewComponent(ISettingService settingService,UserManager<AppUser> userManager)
        {
            _settigservice = settingService;
            _userManager = userManager;


        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

            AppUser user=new AppUser();
            if (User.Identity.IsAuthenticated)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
            }
            

            Dictionary<string, string> settings = await _settigservice.GetAllAsync();
            HeaderVM response = new()
            {
                Settings = settings,
                UserFullName= user.FullName
            };
            return await Task.FromResult(View(response));
        }
        public class HeaderVM
        {


            public Dictionary<string, string> Settings { get; set; }
            public string UserFullName { get; set; }
            public bool IsAuthenticated { get; set; }
        }


    }
    
}

E_Learning-MVC-Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>eLEARNING - eLearning HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
      rel="stylesheet"
    />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet" />
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet" />
  </head>

  <body>
    @await Component.InvokeAsync("Header")
            @RenderBody()
   
    @await Component.InvokeAsync("Footer")
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"
      ><i class="bi bi-arrow-up"></i
    ></a>

    <!-- JavaScript Libraries -->
    <script src=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js" integrity="sha256-8X2C/9AnApQ49JuVtuvXx5dTlg7HhvUCBY4H2os24ks=" crossorigin="anonymous"></script>

  </body>
</html>